### ISSUE TITLE
config.toml not found 

### ISSUE THREAD

**Issue by parhammhd** [lowercasename/gathio#176]
I have deployed the official Docker image with Docker compose and prepared the config.toml file and the config and images directories as told in the documentation.
My gathio-app container goes in a restarting loop and Docker logs shows a sentence asking if I have renamed config-example.toml to config.toml or not.
What should I do? 

The logs show this:

gathio-app | Configuration file not found! Have you rena
med './config/config-example.toml' to './config/config.t
oml'?

I have the config.toml file in there

**Comment by kangaroo72** [comment]
same issue here... any help would be much appreciated

**Comment by lowercasename** [comment]
Hi there, I can get Gathio to work with Docker with this file structure:

```
.
├── config
│  └── config.toml
├── docker-compose.yml
└── images
```

And this `docker-compose.yml`:

```
volumes:
    mongodb_data_db:

services:
    gathio:
        container_name: gathio-app
        image: ghcr.io/lowercasename/gathio:d7c83d30c36a16dfaed169349d4008bddf9a05fd
        links:
            - mongo
        ports:
            - 3000:3000
        volumes:
            # The path to Gathio's config folder - change to match your system
            - ./config:/app/config
            # The path to Gathio's user-uploaded event images folder - change to match your system
            - ./images:/app/public/events
    mongo:
        container_name: gathio-db
        image: mongo:latest
        volumes:
            - mongodb_data_db:/data/db
```

(Which is unchanged from the default one in the repo in everything except the hash of the Docker image, which pins it to the latest current version: `ghcr.io/lowercasename/gathio:d7c83d30c36a16dfaed169349d4008bddf9a05fd`).

And the standard `config.toml` with the only line changed being:

```
mongodb_url = "mongodb://mongo:27017/gathio"
```

There's useful installation instructions [here](https://docs.gath.io/running-gathio/installation/) if you haven't already seen them. Let me know if you're still struggling!
